mouz/home/urls.py
from . import views
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("results/", views.ResultsView.as_view(), name="results"),
    path("matches/", views.MatchesView.as_view(), name="matches"),
    path("major/", views.MajorView.as_view(), name="major"),
    path("pain/", views.SadView.as_view(), name="sad"),
    path("warnings/", views.WarningsView.as_view(), name="warnings"),
    path("ranking/<int:discord_id>", views.RankingView.as_view(), name="ranking"),
    path("event/<slug:slug>", views.EventView.as_view(), name="event"),
    path("ranking/", views.RankingView.as_view(), name="ranking"),
    path("tasks/", views.ScheduledTasks.as_view(), name="tasks"),
    path("fpeekmsg/", views.fpeek_message, name="fpeekmsg"),
    path("matchwidget/", views.WidgetView.as_view(), name="widget"),
    path("<slug:slug>/", views.SiteView.as_view(), name="site"),
    path("r/<slug:slug>/", views.RedirectView.as_view(), name="redirect"),
    path("team/<slug:team>/", views.TeamView.as_view(), name="team"),
]

mouz/mouz/urls.py
from django.contrib import admin
from django.urls import include, path
from home.api import MatchViewSet
from rest_framework import routers
from ropzpeek.views import FaceitWebhook, QuoteListView, YoutubeWebhook

router = routers.DefaultRouter()
router.register(r"matches", MatchViewSet, basename="match")

urlpatterns = [
    path("competition/", include("top20.urls")),
    path("content/", include("content.urls")),
    path("user/", include("allauth.urls")),
    path("vamouz/", admin.site.urls),
    path("faceit/", FaceitWebhook.as_view(), name="faceit-endpoint"),
    path("youtube/", YoutubeWebhook.as_view(), name="youtube-endpoint"),
    path("quotes/", QuoteListView.as_view(), name="quotes"),
    path("", include("home.urls")),
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

mouz/top20/urls.py
from . import views
from django.urls import path
from django.views.generic import TemplateView

app_name = "top20"
urlpatterns = [
    path("<slug:slug>/", views.CompetitionView.as_view(), name="detail"),
    path("<slug:slug>/submit/", views.CompetitionSubmitView.as_view(), name="submit"),
    path(
        "<slug:comp>/<int:pk>-<str:username>",
        views.CompetitionSubmitDetailView.as_view(),
        name="submit-detail",
    ),
]

mouz/top20/models.py
import json
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.db.models import Count, F
from django.utils import timezone
from django.utils.text import slugify
from home.models import BaseEvent
from markdownfield.models import MarkdownField, RenderedMarkdownField
from markdownfield.validators import VALIDATOR_STANDARD


def points_default():
    return {"0": 8, "1": 4, "2": 2, "is_in": 1}


class Competition(BaseEvent):
    val_amount = models.IntegerField(
        default=0, verbose_name="#Slots", help_text="How many slots the competition has"
    )
    extern = models.BooleanField(
        default=False, help_text="Is this a competition hosted on another website?"
    )
    url = models.URLField(
        blank=True, null=True, help_text="URL to the competition if it's external"
    )
    visible = models.BooleanField(
        default=True, help_text="Is the competition visibile to normal users?"
    )
    points = models.JSONField(
        blank=True,
        null=True,
        help_text="""
            maps the deviation of a guess to points, e.g. <b>{"0": 5, "1": 3, "2": 2, "1": 1, "is_in": 0}</b><br/>
            "is_in" key means that the user made a pick which is present somewhere in the result set but outside of the defined deviation classes
        """,
        default=points_default,
    )

    def is_complete(self):
        master = self.compsubmit_set.filter(
            user__username="master", user__is_staff=True
        ).first()
        if master and master.compchoice_set.count() == self.val_amount:
            return True
        return False

    def recalc(self):
        master = (
            get_user_model().objects.filter(username="master", is_staff=True).first()
        )
        for pos in (
            master.compsubmit_set.filter(competition=self).first().compchoice_set.all()
        ):
            for cs in self.compsubmit_set.filter(~models.Q(user=master)):
                correct = cs.compchoice_set.filter(val=pos.val).first()
                if correct:
                    diff = abs(correct.index - pos.index)
                    correct.diff = diff
                    correct.points = self.points.get(str(diff), 0)
                    if correct.points == 0:
                        is_in = self.points.get("is_in")
                        if is_in:
                            correct.points = is_in
                    if diff == 0:
                        correct.correct = True
                    correct.save()

    def get_submissions(self):
        master = (
            get_user_model().objects.filter(username="master", is_staff=True).first()
        )
        return self.compsubmit_set.filter(~models.Q(user=master))

    def get_pick_count(self):
        return (
            self.get_submissions()
            .values("compchoice__val")
            .annotate(player=F("compchoice__val"), count=Count("compchoice"))
            .filter(player__isnull=False)
            .order_by("-count")
            .values("player", "count")
        )

    def get_pick_distribution(self, order_by=["player"]):
        return (
            self.get_submissions()
            .values("compchoice__val", "compchoice__index")
            .annotate(
                index=F("compchoice__index"),
                player=F("compchoice__val"),
                count=Count("compchoice"),
            )
            .filter(player__isnull=False)
            .order_by(*order_by)
            .values("player", "index", "count")
        )


class CompSubmit(models.Model):
    user = models.ForeignKey(
        get_user_model(), null=True, blank=True, on_delete=models.CASCADE
    )
    competition = models.ForeignKey(
        Competition, null=True, blank=True, on_delete=models.CASCADE
    )
    submitted_at = models.DateTimeField(null=True, blank=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    place = models.IntegerField(default=0)
    disqualified = models.BooleanField(default=False)

    def __str__(self):
        return "{} - {}".format(self.competition, self.user)


class CompChoice(models.Model):
    index = models.IntegerField(default=0)
    val = models.CharField(max_length=255)
    csubmit = models.ForeignKey(
        CompSubmit, null=True, blank=True, on_delete=models.CASCADE
    )
    correct = models.BooleanField(default=False)
    diff = models.IntegerField(default=-1)
    points = models.IntegerField(default=0)

    def __str__(self):
        return "{} - {} ({})".format(
            self.csubmit.competition, self.csubmit.user, self.index
        )

    def save(self, *args, **kwargs):
        super(CompChoice, self).save(*args, **kwargs)
        master = (
            get_user_model().objects.filter(username="master", is_staff=True).first()
        )
        if self.csubmit.user == master:
            self.csubmit.competition.recalc()

mouz/top20/forms.py
import logging
from django import forms
from django.core.exceptions import ValidationError
from django.forms import BaseFormSet, formset_factory

logger = logging.getLogger(__name__)


class CompetitionSubmitValueForm(forms.Form):
    name = forms.CharField(
        label="",
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
            }
        ),
    )
    pos = forms.IntegerField(
        label="",
        widget=forms.HiddenInput(),
    )

    def clean(self):
        logger.warning("f clean")
        cleaned_data = super().clean()


class CompetitionFormSet(BaseFormSet):
    def clean(self):
        logger.warning("fs clean")
        if any(self.errors):
            return
        names = []
        for form in self.forms:
            if self.can_delete and self._should_delete_form(form):
                continue
            name = form.cleaned_data.get("name")
            if name == "":
                continue
            if name in names:
                raise ValidationError("Player names in a set must have distinct names")
            names.append(name)

mouz/top20/views.py
import logging
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count, F, Q, Sum, Window
from django.db.models.functions import Coalesce, DenseRank
from django.forms import HiddenInput, IntegerField, TextInput, formset_factory
from django.http import Http404, HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.views.generic.edit import FormMixin, FormView
from top20 import forms, models

logger = logging.getLogger(__name__)


class CompetitionView(generic.DetailView):
    template_name = "top20/competition.html"
    model = models.Competition

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["participants"] = (
            self.object.compsubmit_set.exclude(
                user__username="master", user__is_staff=True
            )
            .annotate(
                sum_points=Coalesce(Sum("compchoice__points"), 0),
                correct_picks=Count(
                    "compchoice__id", filter=Q(compchoice__correct=True)
                ),
                one_off_picks=Count("compchoice__id", filter=Q(compchoice__diff=1)),
                two_off_picks=Count("compchoice__id", filter=Q(compchoice__diff=2)),
                in_picks=Count("compchoice__id", filter=Q(compchoice__points=1)),
            )
            .annotate(
                dense_rank=Window(
                    expression=DenseRank(),
                    order_by=[
                        F(
                            "sum_points",
                        ).desc(),
                        F(
                            "correct_picks",
                        ).desc(),
                        F(
                            "one_off_picks",
                        ).desc(),
                        F(
                            "two_off_picks",
                        ).desc(),
                        F(
                            "in_picks",
                        ).desc(),
                    ],
                )
            )
            .order_by("dense_rank")
        )

        context["active"] = self.object.is_active()
        context["finished"] = self.object.is_finished()
        master = self.object.compsubmit_set.filter(
            user__username="master", user__is_staff=True
        ).first()
        if master:
            context["rn"] = master.compchoice_set.filter(
                csubmit__competition=self.object
            ).count()
        else:
            context["rn"] = 0
        context["total"] = self.object.val_amount
        if self.request.user.is_authenticated:
            submit = self.object.compsubmit_set.filter(user=self.request.user).first()
            context["submit"] = submit
            user = self.object.compsubmit_set.filter(user=self.request.user).first()
            if user:
                context["user_rn"] = (
                    user.compchoice_set.filter(csubmit__competition=self.object)
                    .exclude(val="")
                    .count()
                )
            else:
                context["user_rn"] = 0
        return context


class CompetitionSubmitDetailView(generic.DetailView):
    template_name = "top20/competition_submit_detail.html"
    model = models.CompSubmit

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["guesses"] = self.object.compchoice_set.order_by("index")
        context["correct"] = self.object.compchoice_set.filter(correct=True).count()
        context["points"] = self.object.compchoice_set.aggregate(
            points=Coalesce(Sum("points"), 0)
        ).get("points", 0)
        context["is_active"] = self.object.competition.is_active()
        master = self.object.competition.compsubmit_set.filter(
            user__username="master", user__is_staff=True
        ).first()
        if master:
            context["rn"] = master.compchoice_set.filter(
                csubmit__competition=self.object.competition
            ).count()
        else:
            context["rn"] = 0
        return context


class CompetitionSubmitView(LoginRequiredMixin, generic.DetailView):
    template_name = "top20/competition_submit.html"
    model = models.Competition

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["active"] = self.object.is_active()
        context["finished"] = self.object.is_finished()
        formset = kwargs.get("form")
        if formset:
            for i, form in enumerate(formset):
                formset[i].fields["name"].label = "#{}".format(str(i + 1))
                logger.warning("added num")
            context["form"] = formset
            for i, form in enumerate(formset):
                logger.warning(form)
                logger.warning(form.fields)
            return context
        if self.request.user.is_authenticated:
            submit = self.object.compsubmit_set.filter(user=self.request.user).first()
            context["submit"] = submit
            formset = formset_factory(forms.CompetitionSubmitValueForm, extra=20)
            formset = formset()
            submit_vals = None
            if submit:
                submit_vals = submit.compchoice_set.all()
            for i, form in enumerate(formset):
                exists = None
                if submit_vals:
                    exists = submit_vals.filter(index=i + 1).first()
                formset[i].fields["name"].label = "#{}".format(str(i + 1))
                if exists:
                    formset[i].fields["name"].widget = TextInput(
                        attrs={
                            "class": "form-control",
                            "disabled": not context["active"],
                            "value": exists.val,
                        }
                    )
                else:
                    formset[i].fields["name"].widget = TextInput(
                        attrs={
                            "class": "form-control",
                            "disabled": not context["active"],
                        }
                    )
                formset[i].fields["pos"].initial = i + 1
            context["form"] = formset
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if not self.object.is_active():
            return HttpResponseRedirect(
                reverse("top20:detail", kwargs={"slug": self.object.slug})
            )
        submit = self.object.compsubmit_set.filter(user=self.request.user).first()
        submit_vals = None
        now = timezone.now()
        if submit:
            submit_vals = submit.compchoice_set.all()
            submit.updated_at = now
        else:
            submit = models.CompSubmit()
            submit.user = request.user
            submit.competition = self.object
            submit.submitted_at = now
            submit.updated_at = now
        submit.save()
        formset = formset_factory(
            forms.CompetitionSubmitValueForm, formset=forms.CompetitionFormSet, extra=20
        )
        form = formset(request.POST)
        logger.warning(request.POST)
        if form.is_valid():
            logger.warning("form valid")
            for f in form:
                name = f.cleaned_data.get("name")
                pos = f.cleaned_data.get("pos")
                exists = None
                if submit_vals:
                    exists = submit_vals.filter(index=pos).first()
                if exists and exists.val != name:
                    if name != "":
                        exists.val = name
                        exists.save()
                    else:
                        exists.delete()
                elif not exists and name != "":
                    exists = models.CompChoice()
                    exists.csubmit = submit
                    exists.index = pos
                    exists.val = name
                    exists.save()
            return HttpResponseRedirect(
                reverse("top20:detail", kwargs={"slug": self.object.slug})
            )
        else:
            logger.warning("form invalid")
            return self.render_to_response(self.get_context_data(form=form))

mouz/top20/templates/top20/competition.html
{% extends "home/base.html" %}
{% load static %}
{% load top20 %}

{% block social_description %}
<meta property="og:description" content="{{ object.name }}">
<meta name="twitter:description" content="{{ object.name }}">
{% endblock %}
{% block breadcrumbs %}
<div class="pl-2 py-1 mb-2" style="width: fit-content; border-radius: 4px; border: 1px solid #363636;width: 100%;">
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="{% url 'home:home' %}" style="color: orange">Home</a></li>
        <li class="is-active"><a href="#" aria-current="page" class="has-text-white">{{ object.name }}</a>
            {% if not object.is_active and not object.is_finished %}
            <span class="tag is-dark ml-2 mouz-tag">Upcoming</span>
            {% elif object.is_finished and object.is_complete %}
            <span class="tag is-danger ml-2 mouz-tag">Finished</span>
            {% elif object.is_finished %}
            <span class="tag is-success ml-2 mouz-tag">Ongoing</span>
            {% else %}
            <span class="tag is-success ml-2 mouz-tag">Live</span>
            {% endif %}
        </li>
    </ul>
</nav>
</div>
{% endblock %}
{% block main_content %}
<div class="box-transparent content mb-3">
    {% if object.desc %}
    {{ object.desc_rendered|safe }}
    <div class="mb-2" style="font-family: monospace; font-size: 12px">
        <span class="has-text-weight-bold">Open for submissions: </span><span>{{ object.starting_at|date:"d.m.y H:i" }} - {{ object.ending_at|date:"d.m.y H:i" }} (CET)</span>
    </div>
    {% if object.url %}
    <div>
        <span class="has-text-weight-bold">URL:</span> <a target="_blank" href="{{ object.url }}">{{ object.name }}</a>
    </div>
    {% endif %}
    {% endif %}
</div>

{% if active and not finished and not object.extern %}
{% if submit %}
<a class="button is-warning is-fullwidth is-small has-text-weight-bold" href="{% url 'top20:submit' slug=object.slug %}">Edit</a> 
{% elif not request.user.is_authenticated %}
<article class="message is-info mb-3">
    <div class="message-header">
        <p>Login</p>
    </div>
    <div class="message-body">
        You're currenty not logged in. Login with discord on the top right to participate.
    </div>
</article>
{% else %}
<a class="button is-danger is-fullwidth is-small has-text-weight-bold" href="{% url 'top20:submit' slug=object.slug %}">Participate</a>
{% endif %}
{% endif %}

{% if not object.extern %}
{% if active or finished %}
{% if submit %}
<div class="has-text-weight-bold is-size-7 mt-1">Your submit progress</div>
<div class="progress-wrapper">
    <progress class="progress is-warning mt-1 mb-0" value="{{ user_rn }}" max="{{ total }}">{{ user_rn }}/{{ total }}</progress>
    <p class="progress-value has-text-dark">{{ user_rn }}/{{ total }}</p>
</div>
{% endif %}
<div class="has-text-weight-bold is-size-7 mt-1">Competition progress</div>
<div class="progress-wrapper mb-3">
    <progress class="progress is-primary mt-1 mb-0" value="{{ rn }}" max="{{ total }}">{{ rn }}/{{ total }}</progress>
    <p class="progress-value has-text-dark">{{ rn }}/{{ total }}</p>
</div>
{% endif %}
{% if participants and not object.extern %}
{% if submit and finished %}
<article class="message is-info my-3">
    <div class="message-header">
        <p>Your picks</p>
    </div>
    <div class="message-body">
        You can check your picks <a href="{% url 'top20:submit-detail' comp=object.slug pk=submit.pk username=submit.user.username %}">here</a>.
    </div>
</article>
{% endif %}
<div class="box-transparent py-0">
    {% for p in participants %}
    {% if not p.user.username == 'master' or not p.user.is_staff %}
    <div style="display: grid; grid-template-columns: 40px 1fr 180px; height:48px; place-content:center; {% if not forloop.last %}border-bottom: 1px solid rgb(119 136 153 / 20%);{% endif %} align-items: center">
         {% if p.disqualified %}
             <img src="{% static 'home/mouz_small.png' %}" style="height: 30px; border-radius:50px" />
         {% else %}
         <object data="{{ p|get_avatar_url }}" type="image/png" style="height: 30px; border-radius:50px">
             <img src="{% static 'home/mouz_small.png' %}" style="height: 30px; border-radius:50px" />
        </object>
        {% endif %}
        <div class="is-size-6 has-text-weight-bold is-size-7-mobile text-ellipsis" style="display:grid;">
            <span class="text-ellipsis"><a class="{% if p.user == request.user %}has-text-weight-bold has-text-danger{% endif %}" href="{% url 'top20:submit-detail' comp=object.slug pk=p.pk username=p.user.username %}">{{ p.user }}</a></span>
            <span style="line-height: 12px">
            <span class="text-ellipsis is-italic" style="{% if p.disqualified %}text-decoration: line-through red solid 3px; {% endif %}font-size: 8pt; color: lightgrey; font-weight: 300" title="Last edit date">{{ p.updated_at|date:"d.m.y H:i" }} (CET)</span>
            {% if p.disqualified %}
                <span style="color: red; font-size: 8pt"> User got disqualified from the competition due to breaking either competition related or mouz discord rules</span>
            {% endif %}
            </span>
        </div>
        <div style="display: grid; grid-template-columns: 2fr 3fr 3fr; place-items: center;">
            <div class="has-text-weight-bold is-size-5 is-size-6-mobile {% if p.user == request.user %}has-text-weight-bold has-text-danger{% endif %}">#{{ p.dense_rank }}</div>
            <div style="
            display: grid;
            place-items: center;
            "><div style="
            font-size: small;
            color: lightgrey;
            ">CORRECT</div><div class="{% if p.user == request.user %}has-text-weight-bold has-text-danger{% endif %}" title=""><strong>{{ p.correct_picks}}/{{ rn }}</strong></div></div>
            <div style="
            display: grid;
            place-items: center;
            "><div style="
            font-size: small;
            color: lightgrey;
            ">POINTS
            </div><div class="{% if p.user == request.user %}has-text-weight-bold has-text-danger{% endif %}" title="{{ p.sum_points }} points"><strong>{{ p.sum_points }}</strong></div></div>
        </div>
    </div>
    {% endif %}
    {% endfor %}
</div>
{% endif %}
{% endif %}
{% endblock %}

mouz/top20/templates/top20/competition_submit_detail.html
{% extends "home/base.html" %}
{% load bulma_tags %}
{% load top20 %}
{% block breadcrumbs %}
<div class="pl-2 py-1 mb-2" style="width: fit-content; border-radius: 4px; border: 1px solid #363636;width: 100%;">
    <nav class="breadcrumb" aria-label="breadcrumbs">
        <ul>
            <li><a href="{% url 'home:home' %}" style="color: orange">Home</a></li>
            <li><a href="{% url 'top20:detail' slug=object.competition.slug %}" style="color: orange">{{ object.competition }}</a></li>
            <li class="is-active"><a href="#" aria-current="page" class="has-text-white">{{ object.user.username }}</a></li>
        </ul>
    </nav>
</div>
{% endblock %}
{% block main_content %}
<div style="display:grid;grid-template-columns: 1fr 1fr;place-items: center;/* place-content: center; */grid-template-rows: 60px;grid-gap: 1rem;">
    <div style="
    width: 100%;
    height: 100%;
    display: grid;
    place-content: center;
    border-radius: 4px;
    grid-auto-flow: row;
    "
    class="box-transparent"
    >
        <div class="is-size-5 has-text-centered">{{ correct }}/{{ rn }}</div>
        <div class="is-family-monospace is-size-7">Correct picks</div>
    </div>
    <div style="
    width: 100%;
    height: 100%;
    display: grid;
    place-content: center;
    border-radius: 4px;
    grid-auto-flow: row;
    "
    class="box-transparent"
    >
        <div class="is-size-5 has-text-centered">{{ points }}</div>
        <div class="is-family-monospace is-size-7">Points</div>
    </div>
</div>
{% if not is_active or object.user == request.user %}
<table class="table is-bordered is-fullwidth comp-table has-text-white my-3 box-transparent">
    <thead>
        <tr>
            <th class="has-text-white" style="width: 30px">#</th>
            <th class="has-text-white">Guess</th>
            <th class="has-text-white">HLTV</th>
            <th class="has-text-white" style="width: 30px">Points</th>
        </tr>
    </thead>
    <tbody>
        {% for g in guesses %}
        {% with object.competition|correctPick:g.index as cp %} 
            <tr>
                <td style="width: 30px">{{ g.index }}</td>
                <td style="{% if cp == g.val %}color: green;{% elif g.points > 0 %}color: orange;{% else %}color: red;{% endif %}">{{ g.val }}</td>
                <td>{{ cp }}</td>
                <td style="width: 30px">{{ g.points }}</td>
            </tr>
        {% endwith %}
        {% endfor %}
    </tbody>
</table>
{% else %}
<article class="message is-info my-3">
  <div class="message-header">
      <p>{{ object }}</p>
  </div>
  <div class="message-body">
    You can't view others submits as long as they still can edit it.
  </div>
</article>
{% endif %}
{% endblock %}