mouz/content/urls.py
from . import views
from django.urls import path

app_name = "content"
urlpatterns = [
    path("add/", views.ContentCreateView.as_view(), name="add"),
    path("", views.ContentListView.as_view(), name="list"),
]

mouz/home/urls.py
from . import views
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("results/", views.ResultsView.as_view(), name="results"),
    path("matches/", views.MatchesView.as_view(), name="matches"),
    path("major/", views.MajorView.as_view(), name="major"),
    path("pain/", views.SadView.as_view(), name="sad"),
    path("warnings/", views.WarningsView.as_view(), name="warnings"),
    path("ranking/<int:discord_id>", views.RankingView.as_view(), name="ranking"),
    path("event/<slug:slug>", views.EventView.as_view(), name="event"),
    path("ranking/", views.RankingView.as_view(), name="ranking"),
    path("tasks/", views.ScheduledTasks.as_view(), name="tasks"),
    path("fpeekmsg/", views.fpeek_message, name="fpeekmsg"),
    path("matchwidget/", views.WidgetView.as_view(), name="widget"),
    path("<slug:slug>/", views.SiteView.as_view(), name="site"),
    path("r/<slug:slug>/", views.RedirectView.as_view(), name="redirect"),
    path("team/<slug:team>/", views.TeamView.as_view(), name="team"),
]

mouz/mouz/urls.py
from django.contrib import admin
from django.urls import include, path
from home.api import MatchViewSet
from rest_framework import routers
from ropzpeek.views import FaceitWebhook, QuoteListView, YoutubeWebhook

router = routers.DefaultRouter()
router.register(r"matches", MatchViewSet, basename="match")

urlpatterns = [
    path("competition/", include("top20.urls")),
    path("content/", include("content.urls")),
    path("user/", include("allauth.urls")),
    path("vamouz/", admin.site.urls),
    path("faceit/", FaceitWebhook.as_view(), name="faceit-endpoint"),
    path("youtube/", YoutubeWebhook.as_view(), name="youtube-endpoint"),
    path("quotes/", QuoteListView.as_view(), name="quotes"),
    path("", include("home.urls")),
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

mouz/top20/urls.py
from . import views
from django.urls import path
from django.views.generic import TemplateView

app_name = "top20"
urlpatterns = [
    path("<slug:slug>/", views.CompetitionView.as_view(), name="detail"),
    path("<slug:slug>/submit/", views.CompetitionSubmitView.as_view(), name="submit"),
    path(
        "<slug:comp>/<int:pk>-<str:username>",
        views.CompetitionSubmitDetailView.as_view(),
        name="submit-detail",
    ),
]

mouz/home/models.py
import cloudscraper
import json
import logging
import pytz
import re
import redis
import requests
import ssl
from bs4 import BeautifulSoup
from datetime import datetime
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from home.tasks import send_match_msg
from huey.contrib.djhuey import HUEY
from markdownfield.models import MarkdownField, RenderedMarkdownField
from markdownfield.validators import VALIDATOR_NULL, VALIDATOR_STANDARD

rs = redis.Redis(host="redis", port=6379, db=0)
logger = logging.getLogger(__name__)

PROXIES = {
    "http": "http://{}:{}@brd.superproxy.io:33335".format(
        settings.BRIGHTDATA_USER, settings.BRIGHTDATA_PW
    ),
    "https": "http://{}:{}@brd.superproxy.io:33335".format(
        settings.BRIGHTDATA_USER, settings.BRIGHTDATA_PW
    ),
}


class Team(models.Model):
    name = models.CharField(max_length=255)
    no_match_msg = models.CharField(max_length=255, blank=True, null=True)
    hltv_id = models.IntegerField(blank=True, null=True)
    vlr_id = models.IntegerField(blank=True, null=True)
    pl_id = models.IntegerField(blank=True, null=True)
    rank = models.IntegerField(default=99)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Site(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(
        max_length=255,
        unique=True,
        help_text="The slug the site is available through: https://vamouz.de/slug",
    )
    content = MarkdownField(
        rendered_field="content_rendered",
        validator=VALIDATOR_NULL,
        blank=True,
        help_text="Site text",
    )
    content_rendered = RenderedMarkdownField()

    def __str__(self):
        return self.name


class BaseEvent(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True, blank=True, null=True)
    desc = MarkdownField(
        rendered_field="desc_rendered",
        validator=VALIDATOR_NULL,
        blank=True,
        help_text="Event description",
    )
    desc_rendered = RenderedMarkdownField()
    starting_at = models.DateTimeField(null=True, blank=True, help_text="Start date")
    ending_at = models.DateTimeField(null=True, blank=True, help_text="End date")

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(BaseEvent, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def is_active(self):
        now = timezone.now()
        if now > self.starting_at and now < self.ending_at:
            return True
        return False

    def is_finished(self):
        now = timezone.now()
        if now > self.ending_at:
            return True


class Event(BaseEvent):
    data = models.JSONField(blank=True, null=True, default=dict)


class Match(models.Model):
    date = models.DateTimeField(null=True, blank=True)
    date_guessed = models.BooleanField(default=False)
    postponed = models.BooleanField(default=False)
    status = models.CharField(
        max_length=15,
        default="upcoming",
        choices=(
            ("upcoming", "Upcoming"),
            ("finished", "Finished"),
        ),
    )
    game = models.CharField(
        max_length=15,
        default="csgo",
        choices=(
            ("csgo", "CS:GO"),
            ("lol", "League of Legends"),
            ("valo", "Valorant"),
            ("sc2", "StarCraft II"),
            ("wc3", "Warcraft III"),
            ("fortnite", "Fortnite"),
            ("sf", "Street Fighter"),
            ("sim", "Sim Racing"),
            ("dota", "Dota 2"),
        ),
    )
    hltv_id = models.IntegerField(blank=True, null=True)
    esea_id = models.IntegerField(blank=True, null=True)
    vlr_id = models.IntegerField(blank=True, null=True)
    vlr_dach_id = models.IntegerField(blank=True, null=True)
    pl_id = models.IntegerField(blank=True, null=True)
    faceit_id = models.CharField(max_length=255, null=True, blank=True)
    event_url = models.URLField(blank=True, null=True)
    event_name = models.CharField(max_length=255, blank=True, null=True)
    stream = models.URLField(blank=True, null=True)
    hltv_data = models.JSONField(blank=True, null=True, default=dict)
    noti_counter = models.IntegerField(default=0)
    locked = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        orig = Match.objects.filter(pk=self.pk).first()
        super(Match, self).save(*args, **kwargs)
        self.reschedule()

    def __str__(self):
        team_a_name = ""
        team_a = self.teams.filter(slot="a").first()
        if team_a:
            team_a_name = team_a.team.name
        team_b_name = ""
        team_b = self.teams.filter(slot="b").first()
        if team_b:
            team_b_name = team_b.team.name
        return "{} vs. {}".format(team_a_name, team_b_name)

    def update_match(self):
        logger = logging.getLogger(__name__)
        if self.game == "csgo":
            if not self.hltv_id:
                return
            if self.locked:
                return
            scraper = cloudscraper.create_scraper()
            scraper.proxies.update(PROXIES)
            logger.warning("extra fetch {}".format(self))
            MATCH_URL = "http://hltv.org/mobile/MatchInfo?matchId={}".format(
                self.hltv_id
            )
            r = scraper.get(MATCH_URL)
            try:
                data = r.json()
            except:
                logger.warning(
                    "malformed reply for match fetch {}".format(self.hltv_id)
                )
                return
            self.hltv_data = data
            if data.get("match", {}).get("postMatch", False):
                self.status = "finished"
            else:
                self.status = "upcoming"
            starting_at = data.get("match", {}).get("startDateTime")
            schedule = not self.has_notifications()
            if starting_at:
                date = timezone.make_aware(
                    timezone.datetime.fromisoformat(starting_at[:-1]),
                    pytz.timezone("utc"),
                )
                if self.date != date:
                    schedule = True
                self.date = date
            self.save()
            if schedule:
                self.reschedule()
        elif self.game in ["dota", "lol"]:
            if not self.pl_id:
                return
            link = self.get_match_link().get("link")
            if not link:
                return
            logger.warning("extra fetch {}".format(self))
            scraper = cloudscraper.create_scraper()
            r = requests.get(link)
            soup = BeautifulSoup(r.content, "html.parser")
            date = soup.find("span", {"class": "tztime"})["data-time"]
            if not date:
                date = soup.find("span", {"class": "itime"})["data-time"]
            if date:
                date = datetime.utcfromtimestamp(int(date)).replace(tzinfo=pytz.utc)
                schedule = not self.has_notifications()
                if self.date != date:
                    schedule = True
                    self.date = date
                self.save()

            match_data = {}
            match_header = soup.find("div", {"class": "content-match-head"})
            result = match_header.find(
                "div", {"class": "content-match-head-status"}
            ).find_all("span")
            score_a, score_b = 0, 0
            if len(result) > 1:
                split = result[1].text.split(":")
                score_a, score_b = int(split[0]), int(split[1])
            team_a = (
                match_header.find("div", {"class": "content-match-head-team1"})
                .find("h2")
                .text
            )
            team_b = (
                match_header.find("div", {"class": "content-match-head-team2"})
                .find("h2")
                .text
            )
            if team_b in ["MOUZ", "NXT"]:
                team_a, team_b = team_b, team_a
                score_a, score_b = score_b, score_a
            event_box = (
                soup.find("ul", {"class": "breadcrumbs"}).find_all("li")[1].find("a")
            )
            event_url = event_box.attrs.get('href')
            event_name = event_box.span.get_text()
            match_data = {
                "score_a": score_a,
                "score_b": score_b,
                "team_a": team_a,
                "team_b": team_b,
                "event_url": event_url,
                "event_name": event_name,
            }
            print(match_data)
            self.update_data(match_data)
        elif self.game == "valo":
            if not self.vlr_dach_id:
                return
            logger.warning("extra fetch {}".format(self))
            scraper = cloudscraper.create_scraper()
            r = requests.get(
                "https://www.vrldachevolution.gg/matches/{}-vamouz".format(
                    self.vlr_dach_id
                )
            )
            soup = BeautifulSoup(r.content, "html.parser")
            date = soup.find("span", {"class": "tztime"})["data-time"]
            date = datetime.utcfromtimestamp(int(date)).replace(tzinfo=pytz.utc)
            schedule = not self.has_notifications()
            print(date)
            if self.date != date:
                schedule = True
                self.date = date
            self.save()
            if schedule:
                self.reschedule()

    def update_data(self, data):
        if not self.event_url:
            self.event_url = data.get("event_url")
        if not self.event_name:

mouz/home/forms.py
from django import forms

CHANNEL_CHOICES = (
    ("441534100558446598", "#community-talk"),
    ("497900798638817280", "#match-talk"),
    ("489874067470680069", "#memes-and-banter"),
    ("494476435595984904", "#media-and-links"),
    ("484332981192753153", "#bot-commands"),
)


class MessageForm(forms.Form):
    channel = forms.ChoiceField(choices=CHANNEL_CHOICES)
    message = forms.CharField(widget=forms.Textarea)

mouz/home/templates/home/event.html
{% extends "home/base.html" %}
{% load home %}

{% block breadcrumbs %}
<div class="pl-2 py-1 mb-2" style="width: fit-content; border-radius: 4px; border: 1px solid #363636;width: 100%;">
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="{% url 'home:home' %}" style="color: orange">Home</a></li>
        <li class="is-active"><a href="#" aria-current="page" class="has-text-white">{{ object.name }}</a>
        </li>
    </ul>
</nav>
</div>
{% endblock %}

{% block social_description %}
<meta property="og:description" content="{{ object.name }}">
<meta name="twitter:description" content="{{ object.name }}">
{% endblock %}
{% load humanize %}
{% load cache %}
{% load static %}
{% block main_content %}
<div class="box-transparent content mb-3">
    {% if object.desc %}
    {{ object.desc_rendered|safe }}
    <div class="mt-2" style="font-family: monospace; font-size: 12px">
        <span class="has-text-weight-bold">Event date: </span><span>{{ object.starting_at|date:"d.m.y H:i" }} - {{ object.ending_at|date:"d.m.y H:i" }} (CET)</span>
    </div>
    {% if object.url %}
    <div>
        <span class="has-text-weight-bold">URL:</span> <a target="_blank" href="{{ object.url }}">{{ object.name }}</a>
    </div>
    {% endif %}
    {% endif %}
</div>

<h5 class="subtitle is-7 has-text-weight-bold has-text-white mb-1 ml-1">Teams</h5>
<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(min(230px, 100vw), 1fr)); place-content: center; grid-gap: 1rem" class="mb-3">
    {% for t in object.data.teams %}
    <div class="box-transparent" style="display:grid">
        <div class="is-size-6 has-text-weight-bold" style="justify-self: center">{{ t.name }}</div>
        {% for p in t.players %}
        <div style="font-family: monospace; font-size: 10pt;">- {{ p }}</div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
<h5 class="subtitle is-7 has-text-weight-bold has-text-white mb-1 ml-1">Bracket</h5>
<div class="box-transparent py-3" style="overflow: auto">
    <div style="display: grid; grid-gap: 15px; grid-auto-flow: column; min-width: 100%; width: fit-content; justify-content: flex-start; font-family: monospace; font-size: 14px;" class="mb-2">
         {% for br in object.data.bracket %}
         <div style="display: grid; width: 170px; place-content: center; position: relative; font-weight: 600;">
            {{ br.name }}
         </div>
        {% endfor %}
    </div>
    <div style="display: grid; grid-gap: 15px; grid-auto-flow: column; min-width: 100%; width: fit-content; justify-content: flex-start">
    {% for br in object.data.bracket %}
        <div style="display: grid; grid-row-gap: 15px; {% if br.align_top %}align-content: flex-start;{% else %}align-content: space-around;{% endif %} width: 170px; position: relative;">
        {% for m in br.matches %}
        <div class="is-size-7 is-relative is-unselectable is-clickable has-light-border" style="width: 100%; height: auto; grid-template-columns: 1fr 30px; border-radius: 4px; display: grid; min-height: 0px; min-width: 0px; overflow: hidden; border: 1px solid rgba(188,188,188,0.3);">
            <div style="display:grid;">
                <div class="has-text-weight-bold px-1 text-ellipsis" title="{{m.team_a}}">{{ m.team_a}}</div>
                <div class="has-text-weight-bold px-1 text-ellipsis" title="{{m.team_b}}">{{ m.team_b}}</div>
                <div class="" style="line-height: 14px; font-size: 10px;">
                    <div class="pl-1 has-light-border-top" style="border-top: 1px solid rgba(188,188,188,0.3);">
                        <span>
                            {{ m.date }}
                      </span>
                    </div>
                </div>
            </div>
            <div style="display: grid">
                <div style="display: grid; justify-content: flex-end;" class="px-1">
                    <div class="has-text-weight-bold">
                        <span class="score score_a" style="{% if m.score_a > m.score_b %}color: green;{% elif m.score_b > m.score_a %}color: red;{% endif %}">
                            {% if m.score_a %}{{ m.score_a }}{% else %}0{% endif %}
                        </span>
                    </div>
                </div>
                <div style="display: grid; justify-content: flex-end;" class="px-1">
                    <div class="has-text-weight-bold">
                        <span class="score score_a" style="{% if m.score_a > m.score_b %}color: red;{% elif m.score_b > m.score_a %}color: green;{% endif %}">
                            {% if m.score_b %}{{ m.score_b }}{% else %}0{% endif %}
                        </span>
                    </div>
                </div>
                <div class="has-text-weight-light has-light-border-top px-1" style="display: grid; justify-content: flex-end; line-height: 14px; font-size: 10px;border-top: 1px solid rgba(188,188,188,0.3);">
                    <span>
                        BO{{ m.best_of }}
                    </span>
                </div>
            </div>
        </div>
        {% endfor %}
        </div>
    {% endfor %}
</div>
</div>
{% endblock %}

mouz/home/templates/home/new_home.html
{% extends "home/base.html" %}
{% load humanize %}
{% load cache %}
{% load static %}
{% block main_content %}
<div class="content-box mt-1">
    {% cache 10 new_home %}
    <h5 class="subtitle is-7 has-text-weight-bold has-text-white mb-1 ml-1">Discord</h5>
    <div style="display: grid; grid-template-columns: 1fr 1fr; grid-gap: .5rem" class="mb-3">
        <a class="button is-info is-small" href="https://discord.gg/mousesports">
            <span class="icon is-large">
                <ion-icon name="logo-discord" size="large"></ion-icon>
            </span>
            <span class="ml-1">Join Discord</span>
        </a>
        <a class="button is-small is-fullwidth is-danger" href="{% url 'home:ranking' %}">
            <span class="icon is-large">
                <ion-icon name="list" size="large"></ion-icon>
            </span>
            <span class="ml-1">Ranking</span>
        </a>
    </div>
    <h5 class="subtitle is-7 has-text-weight-bold has-text-white mb-1 ml-1 is-hidden">Major letters</h5>
    <div style="display: grid;grid-template-columns: repeat(auto-fit, minmax(min(150px, 100vw), 1fr)); height: fit-content; grid-gap: .5rem;" class="mb-3 is-hidden">
        <div class="box-transparent py-1 px-2 major-letter">
            <img src="{% static 'home/bymas_small.png' %}"/>
            <div class="overlay">
                <a class="button is-danger is-small is-fullwidth" target="_blank" href="{% static 'home/bymas.png' %}">
                    <span>Image</span>
                </a>
                <a class="button is-danger is-small is-fullwidth" target="_blank" href="{% static 'home/bymas.pdf' %}">
                    <span>PDF</span>
                </a>
            </div>
        </div>
        <div class="box-transparent py-1 px-2 major-letter">
            <img src="{% static 'home/frozen_small.png' %}"/>
            <div class="overlay">
                <a class="button is-danger is-small is-fullwidth" target="_blank" href="{% static 'home/frozen.png' %}">
                    <span>Image</span>
                </a>
                <a class="button is-danger is-small is-fullwidth" target="_blank" href="{% static 'home/frozen.pdf' %}">
                    <span>PDF</span>
                </a>
            </div>
        </div>
        <div class="box-transparent py-1 px-2 major-letter">
            <img src="{% static 'home/dexter_small.png' %}"/>
            <div class="overlay">
                <a class="button is-danger is-small is-fullwidth" target="_blank" href="{% static 'home/dexter.png' %}">
                    <span>Image</span>
                </a>
                <a class="button is-danger is-small is-fullwidth" target="_blank" href="{% static 'home/dexter.pdf' %}">
                    <span>PDF</span>
                </a>
            </div>
        </div>
        <div class="box-transparent py-1 px-2 major-letter">
            <img src="{% static 'home/ropz_small.png' %}"/>
            <div class="overlay">
                <a class="button is-danger is-small is-fullwidth" target="_blank" href="{% static 'home/ropz.png' %}">
                    <span>Image</span>
                </a>
                <a class="button is-danger is-small is-fullwidth" target="_blank" href="{% static 'home/ropz.pdf' %}">
                    <span>PDF</span>
                </a>
            </div>
        </div>
        <div class="box-transparent py-1 px-2 major-letter">
            <img src="{% static 'home/acor_small.png' %}"/>
            <div class="overlay">
                <a class="button is-danger is-small is-fullwidth" target="_blank" href="{% static 'home/acor.png' %}">
                    <span>Image</span>
                </a>
                <a class="button is-danger is-small is-fullwidth" target="_blank" href="{% static 'home/acor.pdf' %}">
                    <span>PDF</span>
                </a>
            </div>
        </div>
        <div class="box-transparent py-1 px-2 major-letter">
            <img src="{% static 'home/mithr_small.png' %}"/>
            <div class="overlay">
                <a class="button is-danger is-small is-fullwidth" target="_blank" href="{% static 'home/mithr.png' %}">
                    <span>Image</span>
                </a>
                <a class="button is-danger is-small is-fullwidth" target="_blank" href="{% static 'home/mithr.pdf' %}">
                    <span>PDF</span>
                </a>
            </div>
        </div>
    </div>
    <a class="button is-small is-fullwidth is-danger mb-3 is-hidden" href="{% url 'home:major' %}">All major letters</a>
    <div class="is-hidden">
    <h5 class="subtitle is-7 has-text-weight-bold has-text-white mb-1 ml-1">Competitions</h5>
    {% for c in competitions %}
    <div class="box-transparent mb-3 {% if c.is_active %}is-currently-active{% endif %}" style="display: grid;">
        <div class="has-text-weight-bold">
            <a href="{% url 'top20:detail' slug=c.slug %}">{{ c.name }}</a>
            {% if not c.is_active and not c.is_finished %}
            <span class="tag is-dark ml-2 mouz-tag">Upcoming</span>
            {% elif c.is_finished and c.is_complete %}
            <span class="tag is-danger ml-2 mouz-tag">Finished</span>
            {% elif c.is_finished %}
            <span class="tag is-success ml-2 mouz-tag">Ongoing</span>
            {% else %}
            <span class="tag is-success ml-2 mouz-tag">Live</span>
            {% endif %}
        </div>
        <div style="font-family: monospace; font-size: 12px">{{ c.starting_at|date:"d.m.y" }} - {{ c.ending_at|date:"d.m.y" }}</div>
    </div>
    {% endfor %}
    {% if events %}
    <h5 class="subtitle is-7 has-text-weight-bold has-text-white mb-1 ml-1">Events</h5>
    {% for c in events %}
    <div class="box-transparent mb-3" style="display: grid;">
        <div class="has-text-weight-bold">
            <a href="{% url 'home:event' slug=c.slug %}">{{ c.name }}</a>
            {% if not c.is_active and not c.is_finished %}
            <span class="tag is-dark ml-2 mouz-tag">Upcoming</span>
            {% elif c.is_finished %}
            <span class="tag is-danger ml-2 mouz-tag">Finished</span>
            {% else %}
            <span class="tag is-success ml-2 mouz-tag">Live</span>
            {% endif %}
        </div>
        <div style="font-family: monospace; font-size: 12px">{{ c.starting_at|date:"d.m.y" }} - {{ c.ending_at|date:"d.m.y" }}</div>
    </div>
    {% endfor %}
    {% endif %}
    </div>
</div>
<h5 class="subtitle is-7 has-text-weight-bold has-text-white mb-1 ml-1">Recent mouz-related content - videos, interviews and more</h5>
{% for c in content %}
<div class="box-transparent mb-2" style="display: grid;">
    <div class="has-text-weight-bold">
        <a href="{{ c.url }}" target="_blank">{{ c.name }}</a>
        {% for t in c.tags.all %}
        <a class="tag is-info has-text-weight-bold ml-2 mouz-tag" href="{% url 'content:list' %}?tag={{ t.name }}">{{ t.name }}</a>
        {% endfor %}
    </div>
    <div style="font-family: monospace; font-size: 12px">{{ c.date|date:"d.m.y H:i" }} - submitted by {{ c.user }}</div>
</div>
{% endfor %}
<div style="display: grid; grid-template-columns: 1fr 1fr; grid-gap: .5rem">
    <a class="button is-small is-info is-fullwidth" href="{% url 'content:list' %}">More content</a>
    <a class="button is-small is-fullwidth is-danger" href="{% url 'content:add' %}">Add content</a>
</div>
</div>
{% endcache %}
<script>
    let show_more = false;
    function showMore() {
        let button = document.getElementById('show-more-trigger');
        let content = document.getElementById('more-games');
        console.log(button);
        console.log(content);
        if (show_more) {
            content.classList.add("is-hidden");
            button.text = "Show League of Legends & VALORANT";
        } else {
            content.classList.remove("is-hidden");
            button.text = "Hide League of Legends & VALORANT";
        }
        show_more = !show_more;
    }
    function adaptGrid() {
        let mm = 0;
        document.querySelectorAll(".upcoming").forEach(u => {
            let um = u.querySelectorAll('.match').length;
            if (um > mm) {
                mm = um;
            }
        });
        document.querySelectorAll(".match-wrapper").forEach(mw => {
            mw.style.gridTemplateRows = `${mm*51+40}px 1fr`;
        });
    }
document.addEventListener("DOMContentLoaded", function() {
    adaptGrid();
});
window.addEventListener('resize', r => {
    if (window.outerWidth < 718) {
        document.querySelectorAll(".match-wrapper-lol").forEach(mw => {
            mw.style = null;
        });
    } else {
        adaptGrid()
    }
});
</script>
{% endblock %}

mouz/home/templates/home/sad.html
{% extends "home/base.html" %}
{% load humanize %}
{% load cache %}
{% load static %}
{% block breadcrumbs %}
<div class="pl-2 py-1 mb-2" style="width: fit-content; border-radius: 4px; border: 1px solid #363636;width: 100%;">
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="{% url 'home:home' %}" style="color: orange">Home</a></li>
        <li class="is-active"><a href="#" aria-current="page" class="has-text-white has-text-weight-bold">PAIN</a>
        </li>
    </ul>
</nav>
</div>
{% endblock %}
{% block main_content %}
<div class="box-transparent py-1 px-2" style="display: grid; place-content: center">
    <video loop controls autoplay>
        <source src="{% static 'home/sad-spongebob-mouz.mp4' %}" type="video/mp4">
        Your browser does not support the video tag.
    </video>
</div>
{% endblock %}

mouz/home/templates/home/tasks.html
{% extends "home/base.html" %}
{% load humanize %}
{% load cache %}
{% load static %}
{% load home %}
{% load tz %}
{% block breadcrumbs %}
<div class="pl-2 py-1 mb-2" style="width: fit-content; border-radius: 4px; border: 1px solid #363636;width: 100%;">
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="{% url 'home:home' %}" style="color: orange">Home</a></li>
        <li class="is-active"><a href="#" aria-current="page" class="has-text-white">Scheduled discord notifications</a>
        </li>
    </ul>
</nav>
</div>
{% endblock %}
{% block main_content %}
{% for m, scheduled in tasks.items %}
<div class="box-transparent py-1 px-2 mb-3">
    <div class="has-text-weight-bold is-size-6">{{ m }} - {{ m.get_game_display }} - {{ m.date|date:"d.m.y H:i" }}</div>
    {% for t in scheduled %}
    <div>- {{ t.eta|as_berlin|date:"d.m.y H:i" }}</div>
    {% endfor %}
</div>
{% endfor %}
{% endblock %}