mouz/content/urls.py
from . import views
from django.urls import path

app_name = "content"
urlpatterns = [
    path("add/", views.ContentCreateView.as_view(), name="add"),
    path("", views.ContentListView.as_view(), name="list"),
]

mouz/home/urls.py
from . import views
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

app_name = "home"
urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("results/", views.ResultsView.as_view(), name="results"),
    path("matches/", views.MatchesView.as_view(), name="matches"),
    path("major/", views.MajorView.as_view(), name="major"),
    path("pain/", views.SadView.as_view(), name="sad"),
    path("warnings/", views.WarningsView.as_view(), name="warnings"),
    path("ranking/<int:discord_id>", views.RankingView.as_view(), name="ranking"),
    path("event/<slug:slug>", views.EventView.as_view(), name="event"),
    path("ranking/", views.RankingView.as_view(), name="ranking"),
    path("tasks/", views.ScheduledTasks.as_view(), name="tasks"),
    path("fpeekmsg/", views.fpeek_message, name="fpeekmsg"),
    path("matchwidget/", views.WidgetView.as_view(), name="widget"),
    path("<slug:slug>/", views.SiteView.as_view(), name="site"),
    path("r/<slug:slug>/", views.RedirectView.as_view(), name="redirect"),
    path("team/<slug:team>/", views.TeamView.as_view(), name="team"),
]

mouz/mouz/urls.py
from django.contrib import admin
from django.urls import include, path
from home.api import MatchViewSet
from rest_framework import routers
from ropzpeek.views import FaceitWebhook, QuoteListView, YoutubeWebhook

router = routers.DefaultRouter()
router.register(r"matches", MatchViewSet, basename="match")

urlpatterns = [
    path("competition/", include("top20.urls")),
    path("content/", include("content.urls")),
    path("user/", include("allauth.urls")),
    path("vamouz/", admin.site.urls),
    path("faceit/", FaceitWebhook.as_view(), name="faceit-endpoint"),
    path("youtube/", YoutubeWebhook.as_view(), name="youtube-endpoint"),
    path("quotes/", QuoteListView.as_view(), name="quotes"),
    path("", include("home.urls")),
    path("api/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
]

mouz/content/models.py
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.utils import timezone
from django.utils.text import slugify
from tagulous.models import TagField


class Content(models.Model):
    name = models.CharField(max_length=255)
    url = models.URLField()
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(
        get_user_model(), null=True, blank=True, on_delete=models.CASCADE
    )
    clicks = models.IntegerField(default=0)
    tags = TagField(blank=True)

    def __str__(self):
        return self.name

mouz/content/forms.py
from . import models
from django.forms import ModelForm


class ContentForm(ModelForm):
    class Meta:
        model = models.Content
        fields = ["name", "url", "tags"]
        labels = {
            "name": "Title",
            "url": "Link",
        }
        help_texts = {
            "name": "Please provide a meaningful title",
            "url": "The URL the content is available at",
        }

mouz/content/views.py
from . import forms, models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.core.cache.utils import make_template_fragment_key
from django.dispatch import receiver
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from home.tasks import send_content_msg


class ContentCreateView(LoginRequiredMixin, CreateView):
    model = models.Content
    form_class = forms.ContentForm

    def get_success_url(self):
        return reverse("home:home", kwargs={})

    def form_valid(self, form):
        form.instance.user = self.request.user
        self.object = form.save()
        send_content_msg(self.object.pk)
        return HttpResponseRedirect(self.get_success_url())


class ContentListView(ListView):
    model = models.Content
    paginate_by = 12
    ordering = ["-date"]

    def get_queryset(self):
        queryset = models.Content.objects.all()
        tag = self.request.GET.get("tag")
        if tag:
            queryset = queryset.filter(tags__name__icontains=tag)
        return queryset.distinct().order_by("-date")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["tags"] = models.Content.tags.tag_model.objects.all()
        return context

mouz/content/templates/content/content_form.html
{% extends "home/base.html" %}
{% block extra_head %}
{% endblock %}
{% load bulma_tags %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
<div class="pl-2 py-1 mb-2" style="width: fit-content; border-radius: 4px; border: 1px solid #363636;width: 100%;">
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="{% url 'home:home' %}" style="color: orange">Home</a></li>
        <li class="is-active"><a href="#" aria-current="page" class="has-text-white">Add content</a>
        </li>
    </ul>
</nav>
</div>
{% endblock %}
{% block main_content %}
{% if perms.content.add_content %}
<article class="message is-info mb-3" style="background-color:unset">
  <div class="message-header" style="background-color: #ff0000;">
      <p>Information!</p>
  </div>
  <div class="message-body content" style="background-color: rgb(37 45 57 / 100%); color: white">
      <ul class="mt-0">
          <li style="list-style: disc outside none">
              Please check if the content you want to submit is already listed.
          </li>
          <li style="list-style: disc outside none">
              Use some tags like 'Article', 'Interview', 'Video', 'mouz NXT' or individual player names like 'ropz' or 'JDC' to categorize the content.
          </li>
          <li style="list-style: disc outside none">
              If the content is available on multiple platforms please link the one with the higher quality, e.g. Youtube > Twitch VOD or Twitter Video.
          </li>
          <li style="list-style: disc outside none">
            <strong>If you abuse this in any way, you'll lose your permissions to share content here immediately & permanently!</strong>
          </li>
      </ul>
  </div>
</article>
<form method="POST" class="has-text-white" autocomplete="off">
    <div class="box-transparent">
        {% csrf_token %}
    {{ form|bulma }} 
    </div>
    <button type="submit" name="_submit" class="button is-success mt-2 is-fullwidth">Submit</button>
</form>
{% else %}
<article class="message is-info mb-3" style="background-color:unset">
  <div class="message-header" style="background-color: #ff0000;">
      <p>Insufficient permissions</p>
  </div>
  <div class="message-body content" style="background-color: rgb(37 45 57 / 100%); color: white">
      Hey, you're logged in with a discord account which is not yet allowed to post content here. Just contact me (y0fl0w#1337) on discord to fix that :).
  </div>
</article>
{% endif %}
{% endblock %}

mouz/content/templates/content/content_list.html
{% extends "home/base.html" %}
{% load humanize %}
{% block breadcrumbs %}
<div class="pl-2 py-1 mb-2" style="width: fit-content; border-radius: 4px; border: 1px solid #363636;width: 100%;">
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="{% url 'home:home' %}" style="color: orange">Home</a></li>
        <li class="is-active"><a href="#" aria-current="page" class="has-text-white">Content</a>
        </li>
    </ul>
</nav>
</div>
{% endblock %}

{% block main_content %}
<div class="my-2 box-transparent">
    <a class="tag is-info has-text-weight-bold ml-2 has-text-black mouz-tag" {% if not request.GET.tag %}style="background-color: red"{% endif %} href="{% url 'content:list' %}">All</a>
    {% for t in tags %}
    <a class="tag is-info has-text-weight-bold ml-2 mb-2 has-text-black mouz-tag" {% if request.GET.tag == t.name %}style="background-color: red"{% endif %} href="{% url 'content:list' %}?tag={{ t.name }}">{{ t.name }}</a>
    {% endfor %}
</div>
<a class="box-transparent is-size-6 has-text-weight-bold mt-3" style="display: grid; place-content: center;" href="{% url 'content:add' %}">Add content</a>
<div class="content-box">
    {% for c in object_list %}
        <div class="box-transparent mb-3" style="display: grid; grid-gap: .1rem">
            <div class="has-text-weight-bold">
                <a href="{{ c.url }}" class="mr-1" target="_blank">{{ c.name }}</a>
            </div>
            <div style="font-size: 12px">
                <span title="{{ c.date }}">{{ c.date|naturaltime }}</span>
                {% for t in c.tags.all %}
                <a class="tag is-info has-text-weight-bold mouz-tag has-text-black ml-1" style="background-color: red" href="{% url 'content:list' %}?tag={{ t.name }}">{{ t.name }}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
</div>
{% include "home/pagination.html" %}
{% endblock %}